version: "3.9"
services:
  supermarket-db:
    image: carlostirado/supermarket_db
    ports:
        - 3306:3306
  supermarket-ms:
    image: carlostirado/supermarket_ms
    ports:
      - 4000:4000
    environment:
      - DB_HOST=supermarket-db
      - DB_PORT=3306
      - DB_USER=supermarket
      - DB_PASSWORD=2021
      - DB_NAME=supermarket_db
      - URL=0.0.0.0:4000
    depends_on:
      - "supermarket-db"
  supermarket-api:
    ports:
      - 5000:5000
    depends_on:
      - "supermarket-ms"
    image: carlostirado/supermarket_api
  supermarket-proxy:
    ports:
      - 80:80
    depends_on:
      - "supermarket-api"
    image: carlostirado/supermarket_proxy
  supermarket-wa:
      ports:
        - 8080:8080
      depends_on:
        - "supermarket-ms"
      image: carlostirado/supermarket_wa
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    links:
      - "supermarket-db:db"
    depends_on:
      - "supermarket-db"